<div id="detailsProduit">
                <h1>Administration</h1>
            <p>Location De Matériel De Chantier</p>
       </div>

<section class="category">
    
        <div class="categoryProduct">   
                    <ul>
                    
                    <li id="produit">
                            <a href="administration.php">Produits</a>
                    </li>
                        
                        <li id="cat">Catégories</li>
                        <li id="Particular">Clients Particulier</li>
                        <li id='professional'>Clients Professionnels</li>
                        <li id="ajoutProduit">Ajouter un article à louer</li>
                        <li id="ajoutCat">Ajouter une catégorie</li>
                    </ul>
        </div><!--

                -->
        <div id="resultAdmin" class="categoryProductGrille detailComplementaireProduit">
                
               
        </div>
</section>