<div id="contact">
            <h1>contact</h1>
            <p>Location De Matériel De Chantier</p>
       </div>

       
       <section class="globalInfosService globalInfosContact">
        <div>
                <a class="ajoutParticulier" href="contactParticulier.php">Particulier</a>
                <a class="ajoutProfessionnel" href="contactProfessionnel.php">Professionnel</a>
            </div>
       
            <div class="infosContact infosService">

                <form action="" method="post">
                    <input type="text" name="nom" placeholder="Nom*">
                    <input type="text" name="prenom" placeholder="Prénom*">
                    <input type="tel" name="phone" placeholder="Téléphone*">
                    <input type="email" name="mail" placeholder="Email*">
                    <textarea name="message" cols="30" rows="10">Message*</textarea>
                    <input type="submit" value="Envoyer">
                </form>
            </div>
            <div class="infosContact infosService">
                <h3>Contactez Notre Équipe De Location</h3>
                <div>
                    <p><i class="fas fa-phone-square"></i>&nbsp;&nbsp; Tel : (+33) 01.44.45.43.23</p>
                    <p><i class="fas fa-envelope"></i>&nbsp;&nbsp; Mail : contact@roille.com</p>
                </div>
                <p>Vous avez besoin d’aide pour votre location, ou vous voulez simplement en savoir plus sur 
                    nos offres de location ? Notre équipe est là pour vous aider</p>

                    <a class="categorie" href="http://">nos catégories</a>
                    <a class="contact" href="http://">nous contacter</a>
            </div>
       </section>